print('Hello, world!')
print('What is your name?')
my_name = input('>')
print('It is good to meet you, ' + my_name)
name_length = len(my_name)
print('The length of your name is: '+ str(name_length))
print('What is your age?')
my_age = int(input('>'))
print('You will be ' + str(name_length) + ' in ' + str(name_length - my_age) + ' years! Good luck with that.')
